# Generated by Django 5.1.5 on 2025-02-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0003_alter_planets_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
